### Admin Register Routes
POST http://127.0.0.1:8000/api/register
Content-Type: application/json

{
 "personnel_id": "606099",
 "name": "Abraham Attah",
 "contact": "0248571022",
 "location": "Kasoa",
 "email": "annoyingAbraham@gmail.com",
 "password": "0248571022",
 "position": "Tech Officer",
 "role": false
}

### Another Tech Officer
POST http://127.0.0.1:8000/api/register
Content-Type: application/json

{
 "personnel_id": "606077",
 "name": "Agyeman Asare",
 "contact": "0266469846",
 "location": "Lapaz",
 "email": "asare12@gmail.com",
 "password": "0266469846",
 "position": "Tech Officer",
 "role": false
}


### Add a service 
POST http://127.0.0.1:8000/api/serviceAdd
Content-Type: application/json

{
 "amtPaid": "30",
 "datePaid": "2023-12-05",
 "expireDate": "2023-11-30",
 "package": "Basic",
 "productId": "pro-423819879",
 "startDate": "2023-10-30"
}
